In [ ]:
options(jupyter.rich_display = F)

**IMPORTANT NOTICE:**

- **PLEASE MAKE SURE R THROWS NO ERROR WHEN YOUR R SCRIPT (BEFORE RENAMING TO A TXT FILE) IS SOURCED USING THE SOURCE BUTTON OR ALL LINES IN YOUR SCRIPT ARE EXECUTED**

- **MAKE SURE AL LINES IN YOUR FILE THAT ARE NOT INTENDED TO EXECUTE AS R COMMANDS SHOULD BE COMMENTED OUT WITH "#"**

- **YOU SHOULD NAME THE OBJECTS EXACTLY AS REQUIRED IN THE QUESTION. OTHERWISE, A CORRECT CODE WILL BE RENDERED AS INCORRECT. NOTE THAT R IS CASE SENSITIVE!**

- **THE FUNCTIONS SHOULD "RETURN" REQUESTED VALUES, NOT "PRINT" OR "CAT"**

- **IN THE FOLLOWING QUESTIONS, DO NOT MAKE USE OF GLOBAL VARIABLES, I.E. ALL OBJECTS CREATED IN THE GLOBAL ENVIRONMENT CAN ONLY BE PASSED AS VALUES TO ARGUMENTS OF FUNCTIONS. THE BODY OF THE FUNCTIONS SHOULD NOT REFER TO GLOBAL OBJECTS**

# TRIM THE RIM

Let's have a sample random matrix as such:

```R
set.seed(1)
mat1 <- matrix(sample(1:100, 25, replace = T), nrow = 5)
mat1

     [,1] [,2] [,3] [,4] [,5]
[1,] 27   90   21    50  94  
[2,] 38   95   18    72  22  
[3,] 58   67   69   100  66  
[4,] 91   63   39    39  13  
[5,] 21    7   77    78  27 
```

Please write a function **trimrow**, that takes a single argument named **mat**, a matrix object, and returns the matrix after trimming the first and last rows as such:

```R
trimrow(mat = mat1)

     [,1] [,2] [,3] [,4] [,5]
[1,] 38   95   18    72  22  
[2,] 58   67   69   100  66  
[3,] 91   63   39    39  13  
```

**Hint:** You may use c() and nrow() functions

**Solution:**

In [ ]:
set.seed(1)
mat1 <- matrix(sample(1:100, 25, replace = T), nrow = 5)
mat1

trimrow <- function(mat)
{
    mat[-c(1, nrow(mat)),]
}

trimrow(mat = mat1)

# GET RANGES

Let's have a sample random matrix as such:

```R
set.seed(1)
mat1 <- matrix(sample(1:100, 25, replace = T), nrow = 5)
mat1

     [,1] [,2] [,3] [,4] [,5]
[1,] 27   90   21    50  94  
[2,] 38   95   18    72  22  
[3,] 58   67   69   100  66  
[4,] 91   63   39    39  13  
[5,] 21    7   77    78  27 
```


Please write a function named **ranges** that takes a single argument named **mat**, a matrix object, and returns the difference between the max and min values of each row as such:

```R
ranges(mat1)

[1] 73 77 42 78 71
```

**Hint:** You may use apply() (once or twice), max() and min() functions

**Solution:**

In [ ]:
set.seed(1)
mat1 <- matrix(sample(1:100, 25, replace = T), nrow = 5)
mat1

ranges <- function(mat)
{
    apply(mat, 1, max) - apply(mat, 1, min)
}

ranges(mat1)

# PLATES

Please click on the below link to download the distance2.RData object to your local computer

[distance2.RData](../../file/distance2.RData)

And load the data object to your R environment as such:

```R
load("~/file/distance2.RData")
```

Check that you have the distance2 object now:

```R
distance2[c("istanbul", "ankara", "izmir"), c("istanbul", "ankara", "izmir")]

         istanbul ankara izmir
istanbul   0      349    327  
ankara   349        0    520  
izmir    327      520      0   
```

The numbers show the birdfly distances between the cities in the rows and columns (e.g the distance between İstanbul and Ankara is 349 km). The distance between a city and itself is 0 of course!

Please write a function **plates** that takes two arguments:
- **cities** is a vector of city names (each name inside quotes)
- **dist** is a distance matrix and the default value is our distance2 object

The function should return the plate codes of the cities as such:

```R
plates(cities = c("istanbul", "izmir", "ankara"))

istanbul    izmir   ankara 
      34       35        6 

plates(c("adana"), dist = distance2)

adana 
    1 

plates(c("edirne", "ardahan")) 

edirne ardahan 
    22      75 
```

**Note that, the returned vector has the city names as attributes along with the plate code values. Your code should also return exactly the same for the given argument values**


**Hints:**
- You may use which() function and the fact that the distance of a city to itself is 0
- You can initiate an empty vector object and then construct a for loop across the city names to accumulate the values in that vector object
- distance2 is the global object, dist is the argument to the function. distance2 is passed to the function as the default value of dist argument
- You can also use the apply() function alternatively, without a loop. However the looped version is easier for you to construct
- All city names in row and column names are lower case and feature only ascii characters such as corum, sanliurfa, agri and gumushane.

**Solution:**

In [ ]:
load("~/file/distance2.RData")
distance2[c("istanbul", "ankara", "izmir"), c("istanbul", "ankara", "izmir")]

plates <- function(cities, dist = distance2)
{
    plate <- NULL
    for (i in cities)
    {
        plate <- c(plate, which(dist[i,] == 0))
    }
    
    return(plate)
}

plates(cities = c("istanbul", "izmir", "ankara"))
plates(c("adana"), dist = distance2)
plates(c("edirne", "ardahan"))
plates(c('bursa', 'izmir'))

In [ ]:
apply(distance2[c("istanbul", "izmir", "ankara"),], 1, function(x) which(x == 0))